$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
experiment_name: Rai-Programmers-regression
type: pipeline
inputs:
  target_column_name: score
  my_training_data:
    type: mltable
    path: azureml:train-pgm-rai:1
    mode: direct
  my_test_data:
    type: mltable
    path: azureml:test-pgm-rai:1
    mode: direct

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:cpus-cluster
  continue_on_step_failure: false

jobs:
  
  convert_train_job:
    type: command
    component: azureml:convert_tabular_to_parquet:1
    inputs:
      tabular_dataset_name: train-pgm-rai
  
  convert_test_job:
    type: command
    component: azureml:convert_tabular_to_parquet:1
    inputs:
      tabular_dataset_name: test-pgm-rai
  
  fetch_model_job:
    type: command
    component: azureml:fetch_registered_model:1
    limits:
      timeout: 60
    inputs:
      model_id: rai_programmer_example_reg_1666334612:1

  create_rai_job:
    type: command
    component: azureml:rai_insights_constructor:1
    inputs:
      title: Score prediction for programmers
      task_type: regression
      model_info_path: ${{parent.jobs.fetch_model_job.outputs.model_info_output_path}}
      train_dataset: ${{parent.jobs.convert_train_job.outputs.dataset_output_path}}
      test_dataset: ${{parent.jobs.convert_test_job.outputs.dataset_output_path}}
      target_column_name: ${{parent.inputs.target_column_name}}
      categorical_column_names:  '["location", "job title", "OS", "Employer", "IDE", "Programming language", "style"]'

  explain_01:
    type: command
    component: azureml:rai_insights_explanation:1
    limits:
      timeout: 120
    inputs:
      comment: Some random string
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}

  causal_01:
    type: command
    component: azureml:rai_insights_causal:1
    inputs:
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      treatment_features: '["Number of github repos contributed to", "YOE"]'

  counterfactual_01:
    type: command
    component: azureml:rai_insights_counterfactual:1
    inputs:
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      total_CFs: 10
      desired_range: '[5, 10]' 

  error_analysis_01:
    type: command
    component: azureml:rai_insights_erroranalysis:1
    inputs:
      rai_insights_dashboard: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      filter_features: '["style", "Employer"]'

  gather_01:
    type: command
    component: azureml:rai_insights_gather:1
    inputs:
      constructor: ${{parent.jobs.create_rai_job.outputs.rai_insights_dashboard}}
      insight_1: ${{parent.jobs.causal_01.outputs.causal}}
      insight_2: ${{parent.jobs.counterfactual_01.outputs.counterfactual}}
      insight_3: ${{parent.jobs.error_analysis_01.outputs.error_analysis}}
      insight_4: ${{parent.jobs.explain_01.outputs.explanation}}
